// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import { Block } from '@/types';
	
export const blocks: Block[] = [
{
	name: "auth-1",
	category: 'auth',
	description: "Modern auth page with particle background and social login buttons.",
	block_number: "1"
},
{
	name: "auth-2",
	category: 'auth',
	description: "Modern auth page with testimonial sidebar, social logins, and email signup.",
	block_number: "2"
},
{
	name: "contact-1",
	category: 'contact',
	description: "Elegant contact page with office info, email, phone, and social links.",
	block_number: "1"
},
{
	name: "contact-2",
	category: 'contact',
	description: "Modern contact card with info section and built-in form area.",
	block_number: "2"
},
{
	name: "feature-1",
	category: 'feature',
	description: "Minimal feature card with icon, title, and subtle grid background.",
	block_number: "1"
},
{
	name: "footer-1",
	category: 'footer',
	description: "Clean footer with company links, resources, and social icons.",
	block_number: "1"
},
{
	name: "footer-2",
	category: 'footer',
	description: "Animated footer with link sections, brand logo, and social icons.",
	block_number: "2"
},
{
	name: "footer-3",
	category: 'footer',
	description: "Grid-based footer with social cards, link groups, and copyright bar.",
	block_number: "3"
},
{
	name: "footer-4",
	category: 'footer',
	description: "Multi-column footer with app store buttons, social icons, and link groups.",
	block_number: "4"
},
{
	name: "footer-5",
	category: 'footer',
	description: "Sticky layered footer with gradient background, social icons, and animated link groups.",
	block_number: "5"
},
{
	name: "image-gallery-1",
	category: 'image-gallery',
	description: "Masonry-style responsive gallery using random images with dynamic aspect ratios.",
	block_number: "1"
},
{
	name: "pricing-1",
	category: 'pricing',
	description: "Responsive pricing section with frequency toggle, tooltips, and highlightable plans.",
	block_number: "1"
},
{
	name: "pricing-2",
	category: 'pricing',
	description: "Modular pricing card UI kit with reusable glass-style components and typography helpers.",
	block_number: "2"
},
{
	name: "pricing-3",
	category: 'pricing',
	description: "Three-tier pricing grid with interactive plan cards, badges, and feature lists.",
	block_number: "3"
},
{
	name: "pricing-4",
	category: 'pricing',
	description: "Animated dual pricing cards with motion effects, discount badges, and trust indicator.",
	block_number: "4"
},
{
	name: "testimonials-1",
	category: 'testimonials',
	description: "Infinite vertical testimonial scroller with smooth motion and repeated card animation.",
	block_number: "1"
},
{
	name: "testimonials-2",
	category: 'testimonials',
	description: "Responsive testimonial grid with smooth motion reveal, subtle gradients, and elegant card design.",
	block_number: "2"
},
];