// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import type { Block } from '@/types';

export const blocks: Block[] = [
  {
    "name": "auth-1",
    "category": "auth",
    "description": "Modern auth page with particle background and social login buttons.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/auth/1/page.tsx"
      },
      {
        "type": "component",
        "name": "auth-page.tsx",
        "path": "registry/blocks/auth/1/auth-page.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      }
    ]
  },
  {
    "name": "auth-2",
    "category": "auth",
    "description": "Modern auth page with testimonial sidebar, social logins, and email signup.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/auth/2/page.tsx"
      },
      {
        "type": "component",
        "name": "auth-page.tsx",
        "path": "registry/blocks/auth/2/auth-page.tsx"
      },
      {
        "type": "component",
        "name": "floating-paths.tsx",
        "path": "registry/blocks/auth/2/floating-paths.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      }
    ]
  },
  {
    "name": "contact-1",
    "category": "contact",
    "description": "Elegant contact page with office info, email, phone, and social links.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/contact/1/page.tsx"
      },
      {
        "type": "component",
        "name": "contact.tsx",
        "path": "registry/blocks/contact/1/contact.tsx"
      }
    ]
  },
  {
    "name": "contact-2",
    "category": "contact",
    "description": "Modern contact card with info section and built-in form area.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/contact/2/page.tsx"
      },
      {
        "type": "component",
        "name": "contact-card.tsx",
        "path": "registry/blocks/contact/2/contact-card.tsx"
      }
    ]
  },
  {
    "name": "cta-1",
    "category": "cta",
    "description": "Centered call-to-action bar with bold heading and dual action buttons.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/cta/1/page.tsx"
      },
      {
        "type": "component",
        "name": "cta.tsx",
        "path": "registry/blocks/cta/1/cta.tsx"
      }
    ]
  },
  {
    "name": "cta-2",
    "category": "cta",
    "description": "Minimal call-to-action section with headline, short description, and dual buttons for sales contact and getting started.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/cta/2/page.tsx"
      },
      {
        "type": "component",
        "name": "cta.tsx",
        "path": "registry/blocks/cta/2/cta.tsx"
      }
    ]
  },
  {
    "name": "cta-3",
    "category": "cta",
    "description": "Stylish call-to-action block featuring bordered layout, decorative icons, and clear buttons for contacting sales or getting started.",
    "block_number": "3",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/cta/3/page.tsx"
      },
      {
        "type": "component",
        "name": "cta.tsx",
        "path": "registry/blocks/cta/3/cta.tsx"
      }
    ]
  },
  {
    "name": "cta-4",
    "category": "cta",
    "description": "Modern call-to-action card with rounded edges, subtle shadow, and dual buttons for contacting sales or getting started.",
    "block_number": "4",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/cta/4/page.tsx"
      },
      {
        "type": "component",
        "name": "cta.tsx",
        "path": "registry/blocks/cta/4/cta.tsx"
      }
    ]
  },
  {
    "name": "cta-5",
    "category": "cta",
    "description": "Newsletter subscription section with email input, submit button, and expert avatars for added trust and engagement.",
    "block_number": "5",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/cta/5/page.tsx"
      },
      {
        "type": "component",
        "name": "cta.tsx",
        "path": "registry/blocks/cta/5/cta.tsx"
      }
    ]
  },
  {
    "name": "feature-1",
    "category": "feature",
    "description": "Minimal feature card with icon, title, and subtle grid background.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/feature/1/page.tsx"
      },
      {
        "type": "component",
        "name": "feature-card.tsx",
        "path": "registry/blocks/feature/1/feature-card.tsx"
      }
    ]
  },
  {
    "name": "faqs-1",
    "category": "faqs",
    "description": "Elegant FAQ section with accordion-style questions, smooth transitions, and clear support call-to-action.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/faqs/1/page.tsx"
      },
      {
        "type": "component",
        "name": "faqs-section.tsx",
        "path": "registry/blocks/faqs/1/faqs-section.tsx"
      }
    ]
  },
  {
    "name": "faqs-2",
    "category": "faqs",
    "description": "Split-screen FAQ layout with bordered sections, interactive accordion, and a clean call-to-action footer.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/faqs/2/page.tsx"
      },
      {
        "type": "component",
        "name": "faqs-section.tsx",
        "path": "registry/blocks/faqs/2/faqs-section.tsx"
      }
    ]
  },
  {
    "name": "faqs-3",
    "category": "faqs",
    "description": "Two-column FAQ section featuring bordered layout, vertical guide line, and elegant accordion interactions.",
    "block_number": "3",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/faqs/3/page.tsx"
      },
      {
        "type": "component",
        "name": "faqs-section.tsx",
        "path": "registry/blocks/faqs/3/faqs-section.tsx"
      }
    ]
  },
  {
    "name": "faqs-4",
    "category": "faqs",
    "description": "Multi-category FAQ section with sidebar filters, adaptive accordion layout, and elegant interactive transitions.",
    "block_number": "4",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/faqs/4/page.tsx"
      },
      {
        "type": "component",
        "name": "faqs-section.tsx",
        "path": "registry/blocks/faqs/4/faqs-section.tsx"
      }
    ]
  },
  {
    "name": "faqs-5",
    "category": "faqs",
    "description": "Responsive FAQ section with filters, search, and accordions for quick answers.",
    "block_number": "5",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/faqs/5/page.tsx"
      },
      {
        "type": "component",
        "name": "faqs-section.tsx",
        "path": "registry/blocks/faqs/5/faqs-section.tsx"
      }
    ]
  },
  {
    "name": "footer-1",
    "category": "footer",
    "description": "Clean footer with company links, resources, and social icons.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/footer/1/page.tsx"
      },
      {
        "type": "component",
        "name": "footer.tsx",
        "path": "registry/blocks/footer/1/footer.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      }
    ]
  },
  {
    "name": "footer-2",
    "category": "footer",
    "description": "Animated footer with link sections, brand logo, and social icons.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/footer/2/page.tsx"
      },
      {
        "type": "component",
        "name": "footer.tsx",
        "path": "registry/blocks/footer/2/footer.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      }
    ]
  },
  {
    "name": "footer-3",
    "category": "footer",
    "description": "Grid-based footer with social cards, link groups, and copyright bar.",
    "block_number": "3",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/footer/3/page.tsx"
      },
      {
        "type": "component",
        "name": "footer.tsx",
        "path": "registry/blocks/footer/3/footer.tsx"
      }
    ]
  },
  {
    "name": "footer-4",
    "category": "footer",
    "description": "Multi-column footer with app store buttons, social icons, and link groups.",
    "block_number": "4",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/footer/4/page.tsx"
      },
      {
        "type": "component",
        "name": "footer.tsx",
        "path": "registry/blocks/footer/4/footer.tsx"
      }
    ]
  },
  {
    "name": "footer-5",
    "category": "footer",
    "description": "Sticky layered footer with gradient background, social icons, and animated link groups.",
    "block_number": "5",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/footer/5/page.tsx"
      },
      {
        "type": "component",
        "name": "sticky-footer.tsx",
        "path": "registry/blocks/footer/5/sticky-footer.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      }
    ]
  },
  {
    "name": "header-1",
    "category": "header",
    "description": "Responsive sticky header with scroll blur effect, animated mobile menu, and adaptive navigation links.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/header/1/page.tsx"
      },
      {
        "type": "component",
        "name": "header.tsx",
        "path": "registry/blocks/header/1/header.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      },
      {
        "type": "component",
        "name": "menu-toggle-icon.tsx",
        "path": "components/menu-toggle-icon.tsx"
      },
      {
        "type": "hook",
        "name": "use-scroll.ts",
        "path": "hooks/use-scroll.ts"
      }
    ]
  },
  {
    "name": "header-2",
    "category": "header",
    "description": "Elegant responsive header with scroll-based styling, mobile drawer menu, and smooth transitions.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/header/2/page.tsx"
      },
      {
        "type": "component",
        "name": "header.tsx",
        "path": "registry/blocks/header/2/header.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      },
      {
        "type": "component",
        "name": "menu-toggle-icon.tsx",
        "path": "components/menu-toggle-icon.tsx"
      },
      {
        "type": "hook",
        "name": "use-scroll.ts",
        "path": "hooks/use-scroll.ts"
      }
    ]
  },
  {
    "name": "header-3",
    "category": "header",
    "description": "Feature-rich responsive header with scroll blur, animated mobile drawer, and nested navigation menus.",
    "block_number": "3",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/header/3/page.tsx"
      },
      {
        "type": "component",
        "name": "header.tsx",
        "path": "registry/blocks/header/3/header.tsx"
      },
      {
        "type": "component",
        "name": "logo.tsx",
        "path": "components/logo.tsx"
      },
      {
        "type": "component",
        "name": "menu-toggle-icon.tsx",
        "path": "components/menu-toggle-icon.tsx"
      },
      {
        "type": "hook",
        "name": "use-scroll.ts",
        "path": "hooks/use-scroll.ts"
      }
    ]
  },
  {
    "name": "image-gallery-1",
    "category": "image-gallery",
    "description": "Masonry-style responsive gallery using random images with dynamic aspect ratios.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/image-gallery/1/page.tsx"
      },
      {
        "type": "component",
        "name": "image-gallery.tsx",
        "path": "registry/blocks/image-gallery/1/image-gallery.tsx"
      },
      {
        "type": "component",
        "name": "lazy-image.tsx",
        "path": "registry/blocks/image-gallery/1/lazy-image.tsx"
      }
    ]
  },
  {
    "name": "logo-cloud-1",
    "category": "logo-cloud",
    "description": "Simple logo grid displaying brand icons in a clean, bordered layout with light and dark mode support.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/logo-cloud/1/page.tsx"
      },
      {
        "type": "component",
        "name": "logo-cloud.tsx",
        "path": "registry/blocks/logo-cloud/1/logo-cloud.tsx"
      }
    ]
  },
  {
    "name": "logo-cloud-2",
    "category": "logo-cloud",
    "description": "Stylish logo grid featuring top tech brands with decorative plus icons and dynamic borders for a modern visual layout.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/logo-cloud/2/page.tsx"
      },
      {
        "type": "component",
        "name": "logo-cloud.tsx",
        "path": "registry/blocks/logo-cloud/2/logo-cloud.tsx"
      }
    ]
  },
  {
    "name": "logo-cloud-3",
    "category": "logo-cloud",
    "description": "Smooth infinite-scrolling logo showcase highlighting trusted brands with gradient masking and elegant motion effects.",
    "block_number": "3",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/logo-cloud/3/page.tsx"
      },
      {
        "type": "component",
        "name": "logo-cloud.tsx",
        "path": "registry/blocks/logo-cloud/3/logo-cloud.tsx"
      }
    ]
  },
  {
    "name": "logo-cloud-4",
    "category": "logo-cloud",
    "description": "Animated logo carousel with soft edge blurs and gradient accents for a sleek, modern brand showcase.",
    "block_number": "4",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/logo-cloud/4/page.tsx"
      },
      {
        "type": "component",
        "name": "logo-cloud.tsx",
        "path": "registry/blocks/logo-cloud/4/logo-cloud.tsx"
      }
    ]
  },
  {
    "name": "not-found-1",
    "category": "not-found",
    "description": "Minimal 404 error page with bold typography, subtle borders, and clear navigation actions.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/not-found/1/page.tsx"
      },
      {
        "type": "component",
        "name": "not-found.tsx",
        "path": "registry/blocks/not-found/1/not-found.tsx"
      }
    ]
  },
  {
    "name": "not-found-2",
    "category": "not-found",
    "description": "Animated 404 page with floating gradient orbs, soft motion effects, and clean centered layout.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/not-found/2/page.tsx"
      },
      {
        "type": "component",
        "name": "not-found.tsx",
        "path": "registry/blocks/not-found/2/not-found.tsx"
      }
    ]
  },
  {
    "name": "pricing-1",
    "category": "pricing",
    "description": "Responsive pricing section with frequency toggle, tooltips, and highlightable plans.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/pricing/1/page.tsx"
      },
      {
        "type": "component",
        "name": "pricing-section.tsx",
        "path": "registry/blocks/pricing/1/pricing-section.tsx"
      },
      {
        "type": "component",
        "name": "frequency-toggle.tsx",
        "path": "registry/blocks/pricing/1/frequency-toggle.tsx"
      }
    ]
  },
  {
    "name": "pricing-2",
    "category": "pricing",
    "description": "Modular pricing card UI kit with reusable glass-style components and typography helpers.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/pricing/2/page.tsx"
      },
      {
        "type": "component",
        "name": "pricing-card.tsx",
        "path": "components/pricing-card.tsx"
      }
    ]
  },
  {
    "name": "pricing-3",
    "category": "pricing",
    "description": "Three-tier pricing grid with interactive plan cards, badges, and feature lists.",
    "block_number": "3",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/pricing/3/page.tsx"
      },
      {
        "type": "component",
        "name": "pricing-section.tsx",
        "path": "registry/blocks/pricing/3/pricing-section.tsx"
      },
      {
        "type": "component",
        "name": "pricing-card.tsx",
        "path": "components/pricing-card.tsx"
      }
    ]
  },
  {
    "name": "pricing-4",
    "category": "pricing",
    "description": "Animated dual pricing cards with motion effects, discount badges, and trust indicator.",
    "block_number": "4",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/pricing/4/page.tsx"
      },
      {
        "type": "component",
        "name": "pricing-section.tsx",
        "path": "registry/blocks/pricing/4/pricing-section.tsx"
      }
    ]
  },
  {
    "name": "testimonials-1",
    "category": "testimonials",
    "description": "Infinite vertical testimonial scroller with smooth motion and repeated card animation.",
    "block_number": "1",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/testimonials/1/page.tsx"
      },
      {
        "type": "component",
        "name": "testimonials-columns.tsx",
        "path": "registry/blocks/testimonials/1/testimonials-columns.tsx"
      }
    ]
  },
  {
    "name": "testimonials-2",
    "category": "testimonials",
    "description": "Responsive testimonial grid with smooth motion reveal, subtle gradients, and elegant card design.",
    "block_number": "2",
    "files": [
      {
        "type": "page",
        "name": "page.tsx",
        "path": "registry/blocks/testimonials/2/page.tsx"
      },
      {
        "type": "component",
        "name": "testimonials-section.tsx",
        "path": "registry/blocks/testimonials/2/testimonials-section.tsx"
      }
    ]
  }
];
